project_id = "ksakloqmgsumnvxveues"

[functions.upload-to-drive]
verify_jwt = true

[functions.delete-user]
verify_jwt = false

[functions.send-task-notification]
verify_jwt = false

[functions.get-users-with-emails]
verify_jwt = false
